### ISSUE TITLE
Informations about system architecture

### ISSUE THREAD

**Issue by lquinet** [cyphyhouse/Decawave#2]
Is it possible to have more information about the architecture of the system, and more precisely the clock synchronisation of the anchor nodes? Furthermore is it also possible to have more documentation about the source code?

I'am performing an applied research in the field of indoor positioning, and I am very intersested in your project. Here is my email if you want to contact me: loic.quinet@cerisic.be .

**Comment by jpjporto** [comment]
Hi,

I've been meaning to add more documentation to this repo for a while. I've been busy finishing up a paper for another project and I'm attending ACC next week, but I'll start uploading docs later this summer.

For now I recommend checking out the [Bitcraze implementation](https://wiki.bitcraze.io/doc:lps:tdoa:protocol). The implementation here is mostly the same as theirs, with a few code changes to improve performance.

Best,
Joao
