### ISSUE TITLE
Build failed in CoIDE

### ISSUE THREAD

**Issue by GrzegorzDlugosz** [cyphyhouse/Decawave#5]
Hi,
It's great that you left this TDoA implementation open source, i"m very gratefull!
But I have problem with building the TREK_TAG bin file. 
Bin file for TREK_TDOA is in your repository, but there is no bin file for TREK_TAG. I tried to build my own from your .coproj file in CoIDE 1.7.8 with few different versions of GNU Toolchain, but it show me the same error everytime:
C:\program files (x86)\gnu tools arm embedded\arm-none-eabi\lib\armv7-m does not exist
Do you know where is the issue here? I can't find any information of this armv7-m lib.
Or maybe you have TREK_TAG bin file somewhere?
I know Coocox is no longer supported, so I'm thinking about migrating this project to some other IDE, can you recommend me some IDE for this so this migration would be easy? I'm nor advanced in this stuff.
Thanks in advance,
Grzechu

**Comment by jpjporto** [comment]
Hmm, I never that error show up for me. For reference, I am using GNU Tools Arm Embedded version 5.4 2016 q3.
I added the bin file to the repo.

That error sounds like it's trying to find the armv7-m library, which it doesn't make sense. Have you tried deleting all the files and re-cloning the repo? Also, have you double checked the toolchain path option?

As for another IDE, I never looked too much into it. Eclipse should be a decent option, but I don't remember if it is free.

**Comment by GrzegorzDlugosz** [comment]
Thanks so much for the adding bin file to repo!
I just tried downloading repo again and it build without error (with GNU 5.4 2016 q3).
I'm very thankful for your help!

**Comment by GrzegorzDlugosz** [comment]
I have another small issue.
After uploading your software on board, my computer don't see any new hardware after I plugged it in into my computer via micro USB cable. Is it supposed to work with STMicroelectronics Virtual COM Port driver like on original Decawave software or it needs some other driver?
I have an another question, if this supposed to work with DecawaveRTLS software for tracking on PC or is it just working on your software from ROS directory?

**Comment by jpjporto** [comment]
The TREK_TAG code is supposed to work via USB like the original Code (but the output is different). The TREK_TDOA doesn't have USB support.

The code here just works with the ROS software included in the repo. The algorithm implementation is different than the DecawaveRTLS code. Here we have an TDOA algorithm, which allows infinitely many tags, but at a lower accuracy. The default decawave code uses a TOF code, which is more accurate, but only supports up to 10 tags.
